name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y nasm

    - name: Build
      run: make

    - name: Run Hello World
      run: ./build/helloworld

    - name: Run Hello User
      run: |
        ./build/printf "CI Test"
        ./build/printf "CI Test\nCI Test2"
        ./build/printf "CI Test\rHello CI Test2" #buggy
        ./build/printf "CI Test\ttabbbbbbb"
        ./build/printf "CI Test\0 who ?"
        ./build/printf "CI Test\\\t.Escaped"

    - name: Run Sleep
      run: time ./build/sleep 1